### PR TITLE
Update deploy.sh

### PR DESCRIPTION
**Pull request by subhadeep-deyashi**

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Subhadeep, but I prefer it the way it is

**Comment by subhadeep-deyashi** [comment]
Its my first PR. I'm more than happy that I'm able to contribute whether or
not it's useful. Thank you so much for the acknowledgement.

**Comment by gr2m** [comment]
Congratulations on your first pull request :) It was perfect 👌 Just not desired. Often times it's a good idea to create an issue first to ask the maintainers if the change is something they would be interested in, then offer to send a pull request. Good luck!

**Comment by subhadeep-deyashi** [comment]
I actually didn't know any of the process. Thanks a lot for the
information. I'll keep these suggestions in mind the next time.

So according to you I should click that raise issue button to ask for
permission and further insight right?

**Comment by gr2m** [comment]
Yes. If you find something that looks like you could improve, create a new issue about it and offer to send a pull request. For very simple things like a typos you can send a pull request directly

**Comment by subhadeep-deyashi** [comment]
Thanks for your reply. I'll keep these in mind.

**Pull request closed without merging**
