### PR TITLE
Updated new blobUrl to link to correct page

### PR DESCRIPTION
**Pull request by Techforchange**

### CODE REVIEW

**Comment by gr2m** [comment]
Can you test if the payload of the `"create"` event contains the "default_repo" property? Just want to make sure, sometimes the webhook payloads diverge from what’s in the documentation

**Comment by Techforchange** [comment]
@gr2m Just tested it, unfortunately not. The only time I saw it appear was with the first call when we get the context.payload.repository

**Comment by gr2m** [comment]
@Techforchange let me know if you need any help :)

**Comment by arlene-perez** [comment]
@gr2m Currently, the branchUrl test fails because the url that comes back from the API will then go through our code(regex) and return the correctBranch Url. Not too sure how to mimick the failure or whether we need to?

**Pull request merged**
